<a href="https://colab.research.google.com/github/terry0809000/tensorflow22/blob/main/00pytorch_fundationas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [46]:
import datetime

print(f"Notebook last run (end-to-end): {datetime.datetime.now()}")

Notebook last run (end-to-end): 2025-12-30 05:15:11.183490


In [47]:

# Import TensorFlow
import tensorflow as tf
print(tf.__version__) # find the version number (should be 2.x+)

2.19.0


In [48]:
import torch
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
print (torch.__version__)

2.9.0+cpu


In [49]:
##introduction to tensors

##introduction to tensors


In [50]:
#scalar
scalar = torch.tensor (7)
scalar

tensor(7)

In [51]:
scalar.ndim

0

In [52]:
#get tensor back as python int
scalar.item()

7

In [53]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [54]:
vector.ndim

1

In [55]:
vector.shape

torch.Size([2])

In [56]:
MATRIX = torch.tensor ([[7,8],
             [9,10]])
MATRIX


tensor([[ 7,  8],
        [ 9, 10]])

In [57]:
MATRIX.ndim

2

In [58]:
MATRIX.shape

torch.Size([2, 2])

In [59]:
TENSOR = torch.tensor([[[1,2,3],
             [3,6,9],
             [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [60]:
TENSOR.ndim

3

In [61]:
TENSOR.shape

torch.Size([1, 3, 3])

In [62]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [63]:
#RANDOM TENSORS
#WHY RANDOM TENSORS?  RANDOM TENSORS ARE IMPROTANT BECAUSE THE WAY MANY NEURAL NETWROKS LEARN IS THAT THEY START WITH TENSORS FULL OF RANDOM NUMBERS AND THEN ADJUST THOSE RANDOM NUMBERS TO BETTER REPRESENT THE DATA.

In [64]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.4280, 0.0604, 0.4884, 0.3270],
        [0.2295, 0.1781, 0.3751, 0.0072],
        [0.4802, 0.1954, 0.7239, 0.3618]])

In [65]:
random_tensor.ndim

2

In [66]:
random_tensor = torch.rand(1,2,2)
random_tensor

tensor([[[0.4773, 0.6846],
         [0.2827, 0.1082]]])

In [67]:
#create a random_tensor with similar shape to an image tensor

In [68]:
random_image_size_tensor=torch.rand(size=(224,224,3))
random_image_size_tensor.shape,random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [69]:
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [70]:
#cretaing a range of tensors and tensors-like
torch.range(0,10)
one_to_ten = torch.arange(start=0,end=1000,step=77)
one_to_ten

/tmp/ipython-input-1632835914.py:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,10)


tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [71]:
torch.__version__

'2.9.0+cpu'

In [72]:
ten_zeros = torch.zeros_like(input = one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [73]:
float_32_tensor= torch.tensor([3.0,6.0,9.0],
                      dtype=None,
                              device=None,
                              requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [74]:
float_32_tensor.dtype

torch.float32

In [75]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [76]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [77]:
int_32_tensor = torch.tensor([3,6,9],dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [78]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

In [79]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.3892, 0.8215, 0.4960, 0.6474],
        [0.4519, 0.8346, 0.4865, 0.3970],
        [0.2674, 0.4249, 0.3539, 0.4578]])

In [80]:
print(some_tensor)
print(f"Datatype of tensor : {some_tensor.dtype}")
print(f"Datatype of tensor : {some_tensor.size}")
print (f"Device tensor is on : {some_tensor.device}")

tensor([[0.3892, 0.8215, 0.4960, 0.6474],
        [0.4519, 0.8346, 0.4865, 0.3970],
        [0.2674, 0.4249, 0.3539, 0.4578]])
Datatype of tensor : torch.float32
Datatype of tensor : <built-in method size of Tensor object at 0x7db8b754ac60>
Device tensor is on : cpu


In [81]:
#create a tensor
tensor=torch.tensor ([1,2,3])
tensor+10


tensor([11, 12, 13])

In [82]:
#W multiply yensor nu 10
tensor = tensor *10
tensor

tensor([10, 20, 30])

In [83]:
torch.add(tensor,10)

tensor([20, 30, 40])

In [84]:
print(tensor, "*", tensor)
print(f"Equals:{tensor*tensor}")

tensor([10, 20, 30]) * tensor([10, 20, 30])
Equals:tensor([100, 400, 900])


In [86]:
torch.matmul(tensor,tensor)

tensor(1400)

In [88]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i]*tensor[i]
print(value)

tensor(1400)
CPU times: user 1.46 ms, sys: 0 ns, total: 1.46 ms
Wall time: 2.42 ms


In [89]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 906 µs, sys: 0 ns, total: 906 µs
Wall time: 590 µs


tensor(1400)

In [90]:
#shape errors
tensor_A = torch.tensor([[1,2],
                        [3,4],
                        [5,6]])
tensor_B = torch.tensor([[7,10],
                        [8,11],
                        [9,12]])

torch.matmul(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
#to fix our tensor shpae issues we can manipulate the shape of our tensors using a transpose

In [91]:
tensor_B

tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])

In [93]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [94]:
x=torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [95]:
torch.max(x),x.max()
torch.mean (x.type(torch.float32)),x.type(torch.float32).mean()
#the torch.mean() function requires a tensor of float32 datatype to work

(tensor(45.), tensor(45.))

In [96]:
torch.sum(x), x.sum()

(tensor(450), tensor(450))

In [105]:
x=x+1

In [107]:
x.argmin() #find the position in tensor that has the minimum value with argmin-> return)

tensor(0)

In [108]:
x[0]

tensor(1)

In [109]:
x.argmax()

tensor(9)

In [112]:
import torch x =torch.arange(1.,10.)
x,x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [115]:
x_reshaped = x.reshape(1,9)

In [116]:
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [117]:
z=x.view(1,9)
z,z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [118]:
z[:,0]=5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [119]:
x_stacked=torch.stack([x,x,x,x],dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [120]:
x_reshaped.squeeze()

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [121]:
x_reshaped.squeeze().shape

torch.Size([9])

In [122]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

#remove extra dimensions from x_shaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [ ]:
#torch.unsqueeze()-add a single dimension to a target tensor at a specific

In [123]:
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")
#

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [ ]:
#torch.permute - rearrange

In [124]:
x_original = torch.rand(size=(224,224,3))
#permute the original tensor to reaarange the axis or dim order
x_permuted = x_original.permute(2, 0, 1)#shift axis 0to1 1to2 2to0
print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [125]:
x_original[0, 0, 0]= 728218
x_original[0,0,0], x_permuted[0,0,0]

(tensor(728218.), tensor(728218.))

In [ ]:
#indexing with pytorch is similar to indexing with numpy

In [126]:
import torch
x=torch.arange(1,10).reshape(1,3,3)
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [127]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [128]:
#let's index on middle bracket(dim=1)
x[0][0]

tensor([1, 2, 3])

In [129]:
x[0][0][0]
#let's index on the most inner bracket(last dimension)

tensor(1)

In [131]:
#use : to select all of a target dimension
x[:,0]
#get all values of 0th and 1st dimensions but only index 1 or 2nd dimensions
x[:,:,1]

tensor([[2, 5, 8]])

In [132]:
#get all values of the 0 dimensions but only the 1 index value of 1st and 2nd dimension
x[:,1,1]

tensor([5])

In [133]:
#get index 0 or 0th and 1st dimension and all valyues of 2nd dimensions
x[0,0,:]

tensor([1, 2, 3])

In [134]:
#index on x to return 9
print(x[0][2][2])

tensor(9)


In [ ]:
#pytorch tensors & numpy

In [137]:
import torch
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array,tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [138]:
array.dtype

dtype('float64')

In [139]:
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))